### PR TITLE
Include a fuzzy finder in the list command. Show seconds until OTP is invalid.

### PR DESCRIPTION
**Pull request by bugbounce**
This is a crude attempt to make it easier to navigate through Namespaces and accounts.
Haven't yet figured a clean way to periodically refresh the finder screen.

### CODE REVIEW

**Comment by bugbounce** [comment]
Hey...Is this something you are interested in ?

**Review by yitsushi — CHANGES_REQUESTED** [review]
The idea is good, I like it, but I would prefer to put this functionality behind a flag or as a new command like `search`.

For me, I use the list command integrated with tmux and aws tools and in case I don't specify the namespace, I just want a list of namespaces without any extras. I have a huge python package with a lot of commands and as an example one of them is split my tmux, ask me what to do, asks for password and then it sends the generated code to a different pane.

**Comment by bugbounce** [comment]
Fair enough. I can imagine that use case for myself as well. Thanks.  How about a `--interactive` flag in the list command ?

**Comment by yitsushi** [comment]
I would prefer the "search" instead of list, because that reflect the functionality better. Maybe it can even search the whole stuff together with fuzzy search like an aggregated "namespace/account" list, that way we don't even have to select the namespace first. It can get a `--generate` flag and it can generate the key on select. Idea?

**Comment by bugbounce** [comment]
Closing this. Since the fuzzyfinder library doesn't yet support any additional keybindings like fzf, this doesn't work for me. I have resorted to local changes and a shell function. Thanks for your inputs.

**Pull request closed without merging**
